use clap::{arg, Command};
use gcode_converter::configuration;

fn main() {
    let matches = Command::new("GCode converter")
        .version("0.0")
        .author("Lasse Bloch. <lassebloch@gmail.com>")
        .about("Converts gcode generated by Inkscape into something that Klipper will accept")
        .arg(
            arg!(-r --replace_gcode ... "Replace all G-codes with the format G0X with GX")
                .required(false),
        )
        .arg(arg!(-f --input_file <FILE> "Original G-code file"))
        .arg(arg!(-o --output_file <FILE> "Output file").required(false))
        .get_matches();

    let replace_gcode = matches.is_present("replace_gcode");
    let input_file = matches.value_of("input_file").expect("required");
    let input_file = String::from(input_file);
    let output_file = matches.value_of("output_file");

    let conf = configuration::Configuration::new(replace_gcode, input_file, output_file);

    gcode_converter::convert_file(conf);
}
